### PR TITLE
improve cicd/remove travis

### PR DESCRIPTION
**Pull request by yanndegat**

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#35.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#35.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#37.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#37.0 ✔ 
* 
  * checks ✔

**Review by pgaxatte — APPROVED** [review]

**Pull request merged**
