### PR TITLE
[DNS Record] add warning on `Change in text format` feature from the web console

### PR DESCRIPTION
**Pull request by yomovh**
# Description

Related to #275 
Add some documentation on a bulk record update feature in the web console that update the ids of the records leading to error in terraform afterwards

- [x ] Documentation update

# How Has This Been Tested?
N/A

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1603.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1603.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1604.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1603.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1604.0 ■   
* 
  * checks ■

**Review by scraly — CHANGES_REQUESTED** [review]

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1613.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1612.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1613.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1613.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1613.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1612.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1612.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1612.0 ■   
* 
  * checks ■

**Review by scraly — APPROVED** [review]
Thanks!

**Pull request merged**
