### PR TITLE
fix: iam policy sweep

### PR DESCRIPTION
**Pull request by fehrnah**
# Description

fixes the iam policies sweeper

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [x] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1823.0 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1824.1 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1824.2 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1831.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1831.0 ✘  
* 
  * checks ✘

**Review by scraly — APPROVED** [review]
Now pre sweepers for ovh_iam_policy are OK

```
2023/07/05 13:45:58 [DEBUG] Running Sweeper (ovh_iam_policy) in region (1)
2023/07/05 13:45:58 [DEBUG] Logged in on OVH API
2023/07/05 13:45:58 [DEBUG] Completed Sweeper (ovh_iam_policy) in region (1) in 379.766833ms
```

**Pull request merged**
