### PR TITLE
Adding gateway and gateway interface resources

### PR DESCRIPTION
**Pull request by durandx**
Adding 2 new resources : 
* ovh_cloud_project_gateway
* ovh_cloud_project_gateway_interface

### CODE REVIEW

**Comment by scraly** [comment]
Hi,
thanks for your pull request.

Can you add unit tests for each of the new resources,
and also documentation pages?

Moreover, if you add two new resources, having datasources can be useful has well.

Thanks :)

**Review by scraly — CHANGES_REQUESTED** [review]
Hi,
thanks for your pull request.

Can you add unit tests for each of the new resources,
and also documentation pages?

Moreover, if you add two new resources, having datasources can be useful has well.

Thanks :)

**Comment by yomovh** [comment]
@durandx : did you know that you can already create a gateway with the openstack provider ? 

This page may help https://docs.ovh.com/gb/en/api/terraform-at-ovhcloud/

**Comment by scraly** [comment]
@durandx 

Thanks for the contribution :) 
If you haven't the time to create documentation and acceptance tests, can you copy/paste to us an example of `ovh_cloud_project_gateway` and `ovh_cloud_project_gateway_interface` configuration?

Thanks :)

**Comment by scraly** [comment]
Hi,

I succesfully created a gateway but when I want to create a gateway_interface I have an issue:

```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ovh_cloud_project_gateway.my-gateway will be created
  + resource "ovh_cloud_project_gateway" "my-gateway" {
      + id           = (known after apply)
      + model        = "s"
      + name         = "my_gateway"
      + network_id   = (known after apply)
      + region       = "GRA5"
      + service_name = "xxxx"
      + status       = (known after apply)
      + subnet_id    = (known after apply)
    }

  # ovh_cloud_project_gateway_interface.my-gateway-interface will be created
  + resource "ovh_cloud_project_gateway_interface" "my-gateway-interface" {
      + gateway_id   = (known after apply)
      + id           = (known after apply)
      + ip           = (known after apply)
      + network_id   = (known after apply)
      + region       = "GRA5"
      + service_name = "xxxx"
      + subnet_id    = (known after apply)
    }

  # ovh_cloud_project_network_private.network will be created
  + resource "ovh_cloud_project_network_private" "network" {
      + id                 = (known after apply)
      + name               = "my_private_network"
      + regions            = [
          + "GRA5",
        ]
      + regions_attributes = (known after apply)
      + regions_status     = (known after apply)
      + service_name       = "xxxxx"
      + status             = (known after apply)
      + type               = (known after apply)
      + vlan_id            = 0
    }

  # ovh_cloud_project_network_private_subnet.networksubnet will be created
  + resource "ovh_cloud_project_network_private_subnet" "networksubnet" {
      + cidr         = (known after apply)
      + dhcp         = true
      + end          = "192.168.168.200"
      + gateway_ip   = (known after apply)
      + id           = (known after apply)
      + ip_pools     = (known after apply)
      + network      = "192.168.168.0/24"
      + network_id   = (known after apply)
      + no_gateway   = false
      + region       = "GRA5"
      + service_name = "xxxx"
      + start        = "192.168.168.100"
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ovh_cloud_project_network_private.network: Creating...
ovh_cloud_project_network_private.network: Still creating... [10s elapsed]
ovh_cloud_project_network_private.network: Still creating... [20s elapsed]
ovh_cloud_project_network_private.network: Creation complete after 27s [id=pn-xxxxxx_0]
ovh_cloud_project_network_private_subnet.networksubnet: Creating...
ovh_cloud_project_network_private_subnet.networksubnet: Creation complete after 5s [id=xxxx-xxxx-xxx-xxx-xxx]
ovh_cloud_project_gateway.my-gateway: Creating...
ovh_cloud_project_gateway.my-gateway: Still creating... [10s elapsed]
ovh_cloud_project_gateway.my-gateway: Still creating... [20s elapsed]
ovh_cloud_project_gateway.my-gateway: Creation complete after 24s [id=xx-xx-xx-xx-xxxx]
ovh_cloud_project_gateway_interface.my-gateway-interface: Creating...
╷
│ Error: calling /cloud/project/xxxx/region/GRA5/gateway/xxx-xxxx-xxx-xx-xxxx/interface with params subnetId: xxxxx-xxx-xxxx-xxxx-xxxx:
│ 	 "HTTP Error 409: Client::Conflict: \"conflict: subnet xxxxcxxxxfxxx-xxx-xxxx-xxx already added to gateway\" (X-OVH-Query-Id: EU.ext-xxxxx.xxxx1.cxxxxxxe-xxx-xxx-xxx-xxx)"
│
│   with ovh_cloud_project_gateway_interface.my-gateway-interface,
│   on pr358.tf line 32, in resource "ovh_cloud_project_gateway_interface" "my-gateway-interface":
│   32: resource "ovh_cloud_project_gateway_interface" "my-gateway-interface" {
│
```

**Comment by DrummyFloyd** [comment]
Any update regarding this MR ? would be great to have a native interraction of OVH API for gateway in the provider

**Comment by scraly** [comment]
Hi @rbeuque74 , can you have a look? thanks! :-)

**Comment by DrummyFloyd** [comment]
any update regarding this ?

**Comment by amstuta** [comment]
Closing this PR as it has been replaced by: https://github.com/ovh/terraform-provider-ovh/pull/697

**Pull request closed without merging**
