### PR TITLE
fix: resource_me_identity update

### LINKED ISSUE #441: [BUG] ovh_me_identity_user not updating fields
### Describe the bug
When importing or changing existing ovh_me_identity_user , nothing is updated, besides the terraform output showing the correct changes (tested with description and email). When updating these fields via API directly, the updates are successful.

`curl -X PUT "https://eu.api.ovh.com/v1/me/identity/user/<user>" \
 -H "authorization: Bearer <redacted>"\
 -H "content-type: application/json" \
 -d '{"description":"a changed description","group":"ADMIN","email":"<another>@<email>.com"}' `

### Terraform Version

terraform -v
Terraform v1.5.2
on linux_amd64

### OVH Terraform Provider Version

+ provider registry.terraform.io/ovh/ovh v0.31.0

### Affected Resource(s)

Please list the resources as a list, for example:
- ovh_me_identity_user

If this issue appears to affect multiple resources, it may be an issue with [Terraform's core](https://github.com/hashicorp/terraform).

### Terraform Configuration Files

```hcl
resource "ovh_me_identity_user" "my_user" {
  for_each = {
      <user>: {
        login: "<user>",
        description: "a changed description",
        group: "ADMIN",
        email: "<another>@<email>.com",
        password: "<redacted>",
      },
      <user2>: {
        login: "<user2>",
        description: "a changed description 2",
        group: "ADMIN",
        email: "<another>@<email>.com",
        password: "<redacted>",
      },
  }

  login = each.value["login"]
  description = each.value["description"]
  group = each.value["group"]
  email = each.value["email"]
  password = each.value["password"]
}

# import {
#   to = ovh_me_identity_user.my_user["<user>"]
#   provider = ovh
#   id = "<user>"
# }
```

### Expected Behavior

Fields description and email should have changed

### Actual Behavior

Terraform showed changed successfully applied, while the UI, and also subsequent terraform plans still shows the same changes to apply

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. create a user with the above template (keep description empty)
2. terraform plan --out="tfplan"
3. terraform apply
4. set description, change email
5. terraform plan --out="tfplan"
```Terraform will perform the following actions:

  # ovh_me_identity_user.my_user["<user>"] will be updated in-place
  ~ resource "ovh_me_identity_user" "my_user" {
      + description          = "old description"
      ~ email                = "<oldEmail>" -> "<another>@<email>.com"
        id                   = "<user>"
```
6. terraform apply
```Acquiring state lock. This may take a few moments...
ovh_me_identity_user.my_user["<user>"]: Modifying... [id=<user>]
ovh_me_identity_user.my_user["<user>"]: Modifications complete after 1s [id=<user>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### PR DESCRIPTION
**Pull request by fehrnah**
# Description

A typo in the resource_me_identity resource implementation prevented user update. This PR fixes the typo and other errors rising from the fix.

Fixes  #441

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Identity tests: `make testacc TESTARGS="-run TestAccMeIdentity.*"`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1847.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1847.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1846.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1846.0 ✘  
* 
  * checks ✘

**Comment by scraly** [comment]
user created:
Capture d’écran 2023-08-18 à 14 39 20

user modified:
Capture d’écran 2023-08-18 à 14 40 26

login modified so a new user created/replaced instead:
Capture d’écran 2023-08-18 à 14 40 40

user deleted:
Capture d’écran 2023-08-18 à 14 41 02

Everything id OK for me

Thanks :)

**Pull request merged**
