### PR TITLE
Adding failover IP address data and resource blocks for lookup and at…

### PR DESCRIPTION
**Pull request by stevenleadbeater**
…tachment to existing instances.

NB/ The work covers manipulating existing failover IP addresses only, it does not cover ordering new ones

Additionally bumped `terraform-plugin-sdk` version to mitigate tests failing due to failure described here: https://issueexplorer.com/issue/hashicorp/terraform-provider-local/75

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @stevenleadbeater 

thank you very much for contributing to the provider.
it seems to be great work.

one point though: it seems that the commit updating the vendor deps brings too much stuff in the provider.
i tried locally to bump the sdk from v2.6.1 to v2.9.0 and i dont get the same go.mod

if you don't mind, i'll make a separate PR bumping to v2.9.0 and you then can rebase your PR on it.

is this ok for you ?

i'll start the review soon

**Comment by yanndegat** [comment]
here #235

**Comment by stevenleadbeater** [comment]
@yanndegat sure I'm happy to sort that out, it should all be rebased now

**Comment by yanndegat** [comment]
hi again @stevenleadbeater 

i'm starting to review your PR.

it's seems great. yet there's a flaw in the ovh api representing the failover ip, and my guess is that it will be hard 
to map in a proper terraform resource as there's no method to "delete" or "detach" an ip.

so i would propose to rename the resource in `cloud_project_ip_failover_attach`. if you don't mind.

**Comment by stevenleadbeater** [comment]
Change made, please let me know if you want it rebased or if you're happy to just squash and merge

**Comment by stevenleadbeater** [comment]
Bump, 3 months, no activity, do you want anything else on this or not?

**Comment by stevenleadbeater** [comment]
Hi @yanndegat please let me know if you want anything else on this PR. I'm ready to make any changes you feel necessary

**Comment by yanndegat** [comment]
hi @stevenleadbeater , 

thanks for this. i'll check this next week. Could you just squash your 2 commits please ?

The doc is missing on your ressources. Do you mind adding them in this pr ? 
If you don't have time, then we'll add them in another pr, we'll just have to log an issue to track that they're missing.

thanks again for your great work.

**Comment by stevenleadbeater** [comment]
@yanndegat squashed as per your request and documentation has been added. Please let me know if there's anything else. I've not really done any ruby before so I'm not sure if I got all the template references right. I plagiarised what was already done quite heavily so hopefully it's going to work but I don't know how to check that

**Comment by stevenleadbeater** [comment]
Hi @yanndegat is there anything else you want on this? Please let me know

**Comment by stevenleadbeater** [comment]
Hi @yanndegat I know I keep bugging you, just trying to find out if this is still on your radar. I'll try keep the pings to weekly so just let me know when you have anything you want updated or fixed and I'll get it sorted :smile:

**Comment by yanndegat** [comment]
hi @stevenleadbeater 

thanks again and sorry for all this delay.

LGTM, i'll merge it today.

could you please just rebase your PR on master, instead of merging, to avoid merge commits ?

thanks again

**Comment by stevenleadbeater** [comment]
Thanks @yanndegat rebased as requested

**Pull request merged**
