### PR TITLE
Datasource add vrack cloud project

### PR DESCRIPTION
**Pull request by reneca**
Implementation of the data source ovh_vrack_cloud_project #260

### CODE REVIEW

**Comment by scraly** [comment]
Hi,

thanks for your PR :).

I think a solution can be to call the `/cloud/project/<serviceName>/vrack` API in order to get the vrack associated to your serviceName:
image

Moreover, in order to validate a PR, we need an acceptance test, for new resources and for new datasources please.

Here an example:
https://github.com/ovh/terraform-provider-ovh/pull/276/files#diff-707b805bb2e444d8557c060b5ea335ffc63a7138113c117f8ca9386198b8624c

Thx.

**Review by scraly — CHANGES_REQUESTED** [review]
Please follow the [previous comment](https://github.com/ovh/terraform-provider-ovh/pull/261#issuecomment-1195471969) :)

**Comment by scraly** [comment]
Any news? :)

**Comment by amstuta** [comment]
Closing this PR because this problem is solved in another one that has been merged, see https://github.com/ovh/terraform-provider-ovh/issues/260

**Pull request closed without merging**
