### PR TITLE
Add documentation on multiple providers usage

### PR DESCRIPTION
**Pull request by yomovh**
# Description

Add documentation on multiple providers usage
Remove redundant information (keys in dev section) 

## Type of change

Please delete options that are not relevant.
- [ x] Documentation update

# How Has This Been Tested?

N/A

# Checklist:
N/A

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1702.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1702.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1702.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1701.0 ✘  
* 
  * checks ✘

**Review by scraly — APPROVED** [review]

**Comment by scraly** [comment]
thanks :)

**Pull request merged**
