### PR TITLE
WIP: Implement Kubernetes API resource endpoint for OVH Cloud

### PR DESCRIPTION
**Pull request by PhilippeVienne**
The goal of this pull request is to be able to:

- [x]  Data source an existing kubernetes cluster configuration
- [x]  Manage as a resource a kubernetes cluster
- [x]  Manage as a resource kubernetes nodes inside the cluster

The goal is to implement only existing functionalities of the current OVH API, any other actions on the kubernetes api must be executed with the kubernetes provider

### CODE REVIEW

**Comment by ticapix** [comment]
Hi,

Looks great :) Thanks !
I'll try it and check how it can be merged

**Comment by ticapix** [comment]
Hi @PhilippeVienne 
We haven't forgot and the contribution are most welcomed but I have to learn a lot of thing from scratch to test/merge the PR.
Sorry for the delay.

**Comment by pdesgarets** [comment]
Hi, any update on this ?

**Comment by somaliz** [comment]
Hi @PhilippeVienne @ticapix Any updates on this PR ? Now that the OVH API has added a nodePool option to the KubernetesCluster creation endpoint and the current NodeAPI "**deprecating**" is basically creating a nodePool 

I have started working on this [terraform-provider-ovh-k8s](https://github.com/moveaxlab/terraform-provider-ovh) & i just saw this pull-request any plans, ETA ?!

Thank you

**Comment by oschrenk** [comment]
Would love to see this. Let's hope the implementor and merger can figure something out. 🤞

**Comment by sulphur** [comment]
any news on the progress?

**Comment by mhurtrel** [comment]
@sulphur @oschrenk @pdesgarets  @PhilippeVienne Hi everyone! OVHcloud managed K8s PM here.
Sorry for the delay on this.
Actually, we are in the next couple of weeks and months, changing the way nodes are managed (nodes pools) and cluster created (allowing compatibilty with the vRack). We wanted those key architectural changes to be prodded to then finalize the compatibility with Terraform, and ensure not to prod something that would break in the meantime. We are quite confident in movin on that plan and having Terraform driver ready near october.
Thanks again for your patience and understanding.

**Comment by sulphur** [comment]
hi, yes I understand. I wish you good luck in implementation and hope to test it one day :)

**Comment by PhilippeVienne** [comment]
Hello, due to the major rewrite of the plugin, I have remade a new PR #160

**Pull request closed without merging**
