### PR TITLE
fix bool vals handling

### PR DESCRIPTION
**Pull request by yanndegat**

### CODE REVIEW

**Review by pgaxatte — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#57.0 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#59.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#59.0 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#60.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#60.0 ✘  
* 
  * checks ✘

**Review by pgaxatte — APPROVED** [review]

**Pull request merged**
