### PR TITLE
add retry on kafka topic + clean dead code

### PR DESCRIPTION
**Pull request by lpatte**
# Description

To avoir Conflict error on Kafka Topic, I add a retry logic on this resource

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

-  `make testacc TESTARGS="-run TestAccCloudProjectDatabaseKafkaTopic_basic"`

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1756.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1756.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1755.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1755.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1755.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1757.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1758.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1757.0 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1758.0 ✘  
* 
  * checks ✘

**Review by scraly — APPROVED** [review]

**Pull request merged**
