### PR TITLE
doc: remove warning about IAM beta

### PR DESCRIPTION
**Pull request by fehrnah**
# Description

IAM resources had a warning about a private bets.
The IAM is now in open beta and available to everyone, so the warning is not needed anymore

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#1863.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1863.0 ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1864.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#1864.0 ■   
* 
  * checks ■

**Comment by Stoakes** [comment]
Hello,

Anyone available to merge this one ?

**Review by scraly — APPROVED** [review]

**Comment by scraly** [comment]
Thanks :)

**Pull request merged**
