### PR TITLE
fix: remove deprecated regions & fix documentation with mising region…

### PR DESCRIPTION
**Pull request by scraly**
…s_attributes

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#595.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#595.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#595.0 ■   
* 
  * checks ■

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#595.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#596.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#596.0 ✘  
* 
  * checks ✘

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-check#598.0 ✔ 
* 
  * checks ✔

**Comment by ovh-cds** [comment]
CDS Report terraform-provider-ovh-testacc#598.0 ✔ 
* 
  * checks ✔

**Comment by fredleger** [comment]
a release in order to use this fix in our code ? :-)

**Pull request merged**
